/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */


export interface AbuseReasons {
  abuseReasonId: number | null;
  id: string;
  mask: number | null;
  reasonTextId: number | null;
}

export interface AchievementCategories {
  color: string | null;
  icon: string | null;
  id: number;
  nameId: number | null;
  order: number | null;
  parentId: number | null;
  visibilityCriterion: string | null;
}

export interface AchievementCategoriesAchievementIdsJunction {
  AchievementCategories_id: string | null;
  target_id: string | null;
}

export interface AchievementObjectives {
  achievementId: number | null;
  criterion: string | null;
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface AchievementProgress {
  id: number;
  name: string | null;
  seasonId: number | null;
}

export interface AchievementProgressSteps {
  achievementId: number | null;
  id: number;
  isBuyable: number | null;
  isCosmetic: number | null;
  progressId: number | null;
  score: number | null;
}

export interface AchievementRewards {
  achievementId: number | null;
  criteria: string | null;
  emotesReward: string | null;
  experienceRatio: number | null;
  guildPoints: number | null;
  id: number;
  itemsQuantityReward: string | null;
  itemsReward: string | null;
  kamasRatio: number | null;
  kamasScaleWithPlayerLevel: number | null;
  ornamentsReward: string | null;
  spellsReward: string | null;
  titlesReward: string | null;
}

export interface Achievements {
  accountLinked: number | null;
  categoryId: number | null;
  descriptionId: number | null;
  iconId: number | null;
  id: number;
  level: number | null;
  nameId: number | null;
  order: number | null;
  points: number | null;
}

export interface AchievementsObjectiveIdsJunction {
  Achievements_id: string | null;
  target_id: string | null;
}

export interface AchievementsRewardIdsJunction {
  Achievements_id: string | null;
  target_id: string | null;
}

export interface ActionFilters {
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface ActivitySuggestions {
  categoryId: number | null;
  descriptionId: number | null;
  endDate: number | null;
  icon: string | null;
  id: number;
  isLarge: number | null;
  level: number | null;
  mapId: number | null;
  nameId: number | null;
  startDate: number | null;
}

export interface ActivitySuggestionsCategories {
  id: number;
  nameId: number | null;
  parentId: number | null;
}

export interface AlignmentGift {
  id: number;
  nameId: number | null;
}

export interface AlignmentOrder {
  id: number;
  nameId: number | null;
  sideId: number | null;
}

export interface AlignmentRank {
  descriptionId: number | null;
  id: number;
  minimumAlignment: number | null;
  nameId: number | null;
  orderId: number | null;
}

export interface AlignmentRankJntGift {
  gifts: string | null;
  id: number;
  levels: string | null;
}

export interface AlignmentSides {
  id: number;
  nameId: number | null;
}

export interface AlignmentTitles {
  id: string;
  namesId: string | null;
  shortsId: string | null;
  sideId: number | null;
}

export interface AllianceRankNameSuggestions {
  id: string;
  uiKey: string | null;
}

export interface AllianceRanks {
  gfxId: number | null;
  id: number;
  isModifiable: number | null;
  nameId: number | null;
  order: number | null;
}

export interface AllianceRightGroups {
  id: number;
  nameId: number | null;
  order: number | null;
  rights: string | null;
}

export interface AllianceRights {
  groupId: number | null;
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface AllianceTags {
  id: number;
  nameId: number | null;
  order: number | null;
  typeId: number | null;
}

export interface AllianceTagsTypes {
  id: number;
  nameId: number | null;
}

export interface AlmanaxCalendars {
  descId: string | null;
  id: number;
  nameId: number | null;
  npcId: number | null;
}

export interface AlmanaxCalendarsBonusesIdsJunction {
  AlmanaxCalendars_id: string | null;
  target_id: string | null;
}

export interface AlterationCategories {
  id: number;
  nameId: number | null;
  parentId: number | null;
}

export interface Alterations {
  categoryId: number | null;
  criteria: string | null;
  descriptionId: number | null;
  iconId: number | null;
  id: number;
  isVisible: number | null;
  isWebDisplay: number | null;
  nameId: number | null;
  possibleEffects: string | null;
}

export interface Appearances {
  data: string | null;
  id: number;
  type: number | null;
}

export interface Areas {
  bounds: string | null;
  containHouses: number | null;
  containPaddocks: number | null;
  hasSuggestion: number | null;
  hasWorldMap: number | null;
  id: number;
  nameId: number | null;
  superAreaId: number | null;
  worldmapId: number | null;
}

export interface ArenaLeagueRewards {
  endSeasonRewards: number | null;
  id: number;
  leagueId: number | null;
  seasonId: number | null;
  titlesRewards: string | null;
}

export interface ArenaLeagues {
  highRatingBound: number | null;
  icon: string | null;
  id: number;
  illus: string | null;
  isLastLeague: number | null;
  lowRatingBound: number | null;
  nameId: number | null;
  ornamentId: number | null;
}

export interface ArenaLeagueSeasons {
  beginning: number | null;
  closure: number | null;
  flagObjectId: number | null;
  id: string;
  nameId: string | null;
  resetDate: number | null;
  uid: number | null;
}

export interface Bonuses {
  amount: number | null;
  id: number;
  type: number | null;
}

export interface BonusesAreaCriterion {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BonusesCriterions {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BonusesCriterionsIdsJunction {
  Bonuses_id: string | null;
  target_id: string | null;
}

export interface BonusesEquippedItemCriterion {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BonusesMonsterCriterion {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BonusesMonsterFamilyCriterion {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BonusesQuestCategoryCriterion {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BonusesSubAreaCriterion {
  id: number;
  type: number | null;
  value: number | null;
}

export interface BreachBosses {
  accessCriterion: string | null;
  apparitionCriterion: string | null;
  category: number | null;
  id: number;
  incompatibleBosses: string | null;
  monsterId: number | null;
  rewardId: number | null;
}

export interface BreachDungeonModificators {
  additionalRewardPercent: number | null;
  criterion: string | null;
  id: number;
  isPositiveForPlayers: number | null;
  modificatorId: number | null;
  score: number | null;
  tooltipBaseline: string | null;
}

export interface BreachInfinityLevels {
  id: number;
  level: number | null;
  nameId: number | null;
}

export interface BreachPrizes {
  categoryId: number | null;
  currency: number | null;
  descriptionKey: string | null;
  id: number;
  itemId: number | null;
  nameId: number | null;
  tooltipKey: string | null;
}

export interface BreachWorldMapCoordinates {
  exploredMapIcon: number | null;
  id: number;
  mapCoordinateX: number | null;
  mapCoordinateY: number | null;
  mapStage: number | null;
  unexploredMapIcon: number | null;
}

export interface BreachWorldMapSectors {
  id: number;
  legendId: string | null;
  maxStage: number | null;
  minStage: number | null;
  sectorIcon: string | null;
  sectorNameId: string | null;
}

export interface BreedRoles {
  assetId: number | null;
  color: number | null;
  descriptionId: number | null;
  id: number;
  nameId: number | null;
}

export interface Breeds {
  breedRoles: string | null;
  breedSpellsId: string | null;
  complexity: number | null;
  creatureBonesId: number | null;
  descriptionId: number | null;
  femaleArtwork: number | null;
  femaleColors: string | null;
  femaleLook: string | null;
  gameplayClassDescriptionId: string | null;
  gameplayDescriptionId: string | null;
  guideItemId: number | null;
  id: number;
  longNameId: string | null;
  maleArtwork: number | null;
  maleColors: string | null;
  maleLook: string | null;
  shortNameId: string | null;
  sortIndex: number | null;
  spawnMap: number | null;
  statsPointsForAgility: string | null;
  statsPointsForChance: string | null;
  statsPointsForIntelligence: string | null;
  statsPointsForStrength: string | null;
  statsPointsForVitality: string | null;
  statsPointsForWisdom: string | null;
}

export interface CensoredContents {
  id: string;
  lang: string | null;
  newValue: number | null;
  oldValue: number | null;
  type: number | null;
}

export interface CensoredWords {
  deepLooking: number | null;
  id: number;
  language: string | null;
  listId: number | null;
  word: string | null;
}

export interface Challenges {
  activationCriterion: string | null;
  categoryId: number | null;
  completionCriterion: string | null;
  descriptionId: number | null;
  iconId: number | null;
  id: number;
  incompatibleChallenges: string | null;
  nameId: number | null;
  targetMonsterId: number | null;
}

export interface CharacteristicCategories {
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface CharacteristicCategoriesCharacteristicIdsJunction {
  CharacteristicCategories_id: string | null;
  target_id: string | null;
}

export interface Characteristics {
  asset: string | null;
  categoryId: number | null;
  id: number;
  keyword: string | null;
  nameId: number | null;
  order: number | null;
  scaleFormulaId: number | null;
  upgradable: number | null;
  visible: number | null;
}

export interface CharacterXPMappings {
  experiencePoints: number | null;
  id: string;
  level: number | null;
}

export interface ChatChannels {
  allowObjects: number | null;
  descriptionId: number | null;
  id: number;
  isPrivate: number | null;
  nameId: number | null;
  shortcut: string | null;
  shortcutKey: string | null;
}

export interface Choices {
  choiceNameId: number | null;
  duration: number | null;
  id: number;
  options: string | null;
  proposalCount: number | null;
}

export interface Collectables {
  entityId: number | null;
  gfxId: number | null;
  id: string;
  name: string | null;
  order: number | null;
  rarity: number | null;
  typeId: number | null;
}

export interface Collections {
  collectables: string | null;
  criterion: string | null;
  id: string;
  name: string | null;
  typeId: number | null;
}

export interface CompanionCharacteristics {
  caracId: number | null;
  companionId: number | null;
  id: number;
  order: number | null;
  statPerLevelRange: string | null;
}

export interface Companions {
  assetId: number | null;
  characteristics: string | null;
  creatureBoneId: number | null;
  descriptionId: number | null;
  id: number;
  look: string | null;
  nameId: number | null;
  spells: string | null;
  startingSpellLevelId: number | null;
  visibility: string | null;
  webDisplay: number | null;
}

export interface CompanionSpells {
  companionId: number | null;
  gradeByLevel: string | null;
  id: number;
  spellId: number | null;
}

export interface CreatureBonesOverrides {
  boneId: number | null;
  creatureBoneId: number | null;
  id: string;
}

export interface CreatureBonesTypes {
  creatureBoneId: number | null;
  id: number;
}

export interface CustomModeBreedSpells {
  breedId: number | null;
  id: number;
  isHidden: number | null;
  isInitialSpell: number | null;
  pairId: number | null;
}

export interface DependencyPaths {
  depth: number;
  sourceId: number;
  sourceType: string;
  targetId: number;
  targetType: string;
}

export interface Documents {
  authorId: string | null;
  clientProperties: string | null;
  contentCSS: string | null;
  contentId: string | null;
  id: number;
  showBackgroundImage: number | null;
  showTitle: number | null;
  subTitleId: string | null;
  titleId: string | null;
  typeId: number | null;
}

export interface Dungeons {
  entranceMapId: number | null;
  exitMapId: number | null;
  id: number;
  nameId: number | null;
  optimalPlayerLevel: number | null;
}

export interface DungeonsMapIdsJunction {
  Dungeons_id: string | null;
  target_id: string | null;
}

export interface EffectInstanceDice {
  baseEffectId: number | null;
  delay: number | null;
  diceNum: number | null;
  diceSide: number | null;
  dispellable: number | null;
  displayZero: number | null;
  duration: number | null;
  effectElement: number | null;
  effectId: number | null;
  effectTriggerDuration: number | null;
  effectUid: number | null;
  group: number | null;
  id: string;
  m_flags: number | null;
  modificator: number | null;
  order: number | null;
  random: number | null;
  spellId: number | null;
  targetId: number | null;
  targetMask: string | null;
  triggers: string | null;
  value: number | null;
  zoneDescr: string | null;
}

export interface Effects {
  actionFiltersId: string | null;
  active: number | null;
  bonusType: number | null;
  boost: number | null;
  category: number | null;
  characteristic: number | null;
  characteristicOperator: string | null;
  descriptionId: number | null;
  effectPowerRate: number | null;
  effectPriority: number | null;
  effectTriggerDuration: number | null;
  elementId: number | null;
  forceMinMax: number | null;
  hideValueInTooltip: number | null;
  iconId: number | null;
  id: number;
  isInPercent: number | null;
  oppositeId: number | null;
  showInSet: number | null;
  showInTooltip: number | null;
  textIconReferenceId: number | null;
  theoreticalDescriptionId: string | null;
  theoreticalPattern: number | null;
  useDice: number | null;
  useInFight: number | null;
}

export interface EmblemBackgrounds {
  id: number;
  order: number | null;
}

export interface EmblemSymbolCategories {
  id: number;
  nameId: number | null;
}

export interface EmblemSymbols {
  categoryId: number | null;
  colorizable: number | null;
  iconId: number | null;
  id: number;
  order: number | null;
  skinId: number | null;
}

export interface Emoticons {
  animName: string | null;
  aura: number | null;
  cooldown: number | null;
  duration: number | null;
  eightDirections: number | null;
  id: number;
  nameId: number | null;
  order: number | null;
  persistancy: number | null;
  scale: number | null;
  shortcutId: string | null;
  spellLevelId: number | null;
  weight: number | null;
}

export interface EvolutiveEffects {
  actionId: number | null;
  id: number;
  progressionPerLevelRange: string | null;
  targetId: number | null;
}

export interface EvolutiveItemTypes {
  experienceBoost: number | null;
  experienceByLevel: string | null;
  id: number;
  maxLevel: number | null;
}

export interface ExpeditionSeasons {
  beginning: number | null;
  closure: number | null;
  flagObjectId: number | null;
  id: string;
  nameId: string | null;
  resetDate: number | null;
  uid: number | null;
}

export interface ExternalNotifications {
  categoryId: number | null;
  colorId: number | null;
  defaultEnable: number | null;
  defaultMultiAccount: number | null;
  defaultNotify: number | null;
  defaultSound: number | null;
  descriptionId: number | null;
  iconId: number | null;
  id: number;
  messageId: string | null;
  name: string | null;
}

export interface FeatureDescriptions {
  children: string | null;
  criterion: string | null;
  descriptionId: number | null;
  id: number;
  images: string | null;
  nameId: number | null;
  parentId: number | null;
  priority: number | null;
}

export interface FightScenarios {
  id: number;
  nameId: string | null;
}

export interface FinishMoves {
  category: number | null;
  duration: number | null;
  free: number | null;
  id: number;
  nameId: number | null;
  spellLevel: number | null;
}

export interface ForgettableSpells {
  id: number;
  itemId: number | null;
  pairId: number | null;
}

export interface GuildChestTabs {
  cost: number | null;
  dropRight: number | null;
  gfxId: number | null;
  id: string;
  index: number | null;
  nameId: number | null;
  openRight: number | null;
  seniority: number | null;
  serverType: number | null;
  tabId: number | null;
  takeRight: number | null;
}

export interface GuildRankNameSuggestions {
  id: string;
  uiKey: string | null;
}

export interface GuildRanks {
  gfxId: number | null;
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface GuildRightGroups {
  id: number;
  nameId: number | null;
  order: number | null;
  rights: string | null;
}

export interface GuildRights {
  groupId: number | null;
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface GuildTags {
  id: number;
  nameId: number | null;
  order: number | null;
  typeId: number | null;
}

export interface GuildTagsTypes {
  id: number;
  nameId: number | null;
}

export interface HavenbagFurnitures {
  blocksMovement: number | null;
  cellsHeight: number | null;
  cellsWidth: number | null;
  color: number | null;
  elementId: number | null;
  gfxId: number | null;
  height: number | null;
  horizontalSymmetry: number | null;
  id: string;
  isStackable: number | null;
  layerId: number | null;
  order: number | null;
  origin: string | null;
  size: string | null;
  skillId: number | null;
  themeId: number | null;
  typeId: number | null;
}

export interface HavenbagThemes {
  id: number;
  mapId: number | null;
  nameId: number | null;
}

export interface Heads {
  assetId: string | null;
  breed: number | null;
  gender: number | null;
  id: number;
  label: string | null;
  order: number | null;
  payable: number | null;
  skins: string | null;
}

export interface HintCategory {
  id: number;
  nameId: number | null;
}

export interface Hints {
  categoryId: number | null;
  gfx: number | null;
  id: number;
  level: number | null;
  mapId: number | null;
  nameId: number | null;
  outdoor: number | null;
  realMapId: number | null;
  subareaId: number | null;
  worldMapId: number | null;
  x: number | null;
  y: number | null;
}

export interface Houses {
  defaultPrice: number | null;
  descriptionId: number | null;
  gfxId: number | null;
  id: string;
  nameId: number | null;
  roomCount: number | null;
  typeId: number | null;
}

export interface IncarnationLevels {
  id: number;
  incarnationId: number | null;
  level: number | null;
  requiredXp: number | null;
}

export interface InfoMessages {
  id: string;
  messageId: number | null;
  textId: number | null;
  typeId: number | null;
}

export interface Interactives {
  actionId: number | null;
  displayTooltip: number | null;
  id: number;
  nameId: number | null;
}

export interface Items {
  appearanceId: number | null;
  changeVersion: string | null;
  craftConditional: string | null;
  craftFeasible: string | null;
  craftVisible: string | null;
  craftXpRatio: number | null;
  criteria: string | null;
  criteriaTarget: string | null;
  descriptionId: number | null;
  favoriteRecyclingSubareas: string | null;
  favoriteSubAreas: string | null;
  favoriteSubAreasBonus: number | null;
  iconId: number | null;
  id: number;
  importantNoticeId: string | null;
  isColorable: number | null;
  itemSetId: number | null;
  level: number | null;
  m_flags: number | null;
  nameId: number | null;
  possibleEffects: string | null;
  price: number | null;
  realWeight: number | null;
  recipeSlots: number | null;
  recyclingNuggets: number | null;
  resourcesBySubarea: string | null;
  tooltipExpirationDate: string | null;
  typeId: number | null;
  useAnimationId: number | null;
  visibility: string | null;
}

export interface ItemsDropMonsterIdsJunction {
  Items_id: string | null;
  target_id: string | null;
}

export interface ItemsDropTemporisMonsterIdsJunction {
  Items_id: string | null;
  target_id: string | null;
}

export interface ItemSets {
  bonusIsSecret: number | null;
  effects: string | null;
  id: number;
  items: string | null;
  nameId: number | null;
}

export interface ItemsEvolutiveEffectIdsJunction {
  Items_id: string | null;
  target_id: string | null;
}

export interface ItemsRecipeIdsJunction {
  Items_id: string | null;
  target_id: string | null;
}

export interface ItemSuperTypes {
  id: number;
  possiblePositions: string | null;
}

export interface ItemTypes {
  categoryId: number | null;
  craftXpRatio: number | null;
  evolutiveTypeId: number | null;
  gender: number | null;
  id: number;
  isInEncyclopedia: number | null;
  mimickable: number | null;
  nameId: number | null;
  plural: number | null;
  possiblePositions: string | null;
  rawZone: string | null;
  superTypeId: number | null;
}

export interface Jobs {
  hasLegendaryCraft: number | null;
  iconId: number | null;
  id: number;
  nameId: number | null;
}

export interface KothRoles {
  id: number;
  isDefault: number | null;
  nameId: number | null;
}

export interface LegendaryPowersCategories {
  categoryName: string | null;
  categoryOverridable: number | null;
  categorySpells: string | null;
  id: number;
}

export interface LegendaryTreasureHunts {
  chestId: number | null;
  id: number;
  level: number | null;
  mapItemId: number | null;
  monsterId: number | null;
  nameId: number | null;
  xpRatio: number | null;
}

export interface LivingObjectSkinJntMood {
  id: string;
  moods: string | null;
  skinId: number | null;
}

export interface LuaFormulas {
  formulaName: string | null;
  id: number;
  luaFormula: string | null;
}

export interface MapCoordinates {
  compressedCoords: number | null;
  id: string;
}

export interface MapCoordinatesMapIdsJunction {
  MapCoordinates_id: string | null;
  target_id: string | null;
}

export interface MapPositions {
  fightSnapshot: string | null;
  id: number;
  m_flags: number | null;
  nameId: number | null;
  playlistIds: string | null;
  posX: number | null;
  posY: number | null;
  roleplaySnapshot: string | null;
  subAreaId: number | null;
  tacticalModeTemplateId: number | null;
  worldMap: number | null;
}

export interface MapReferences {
  cellId: number | null;
  id: number;
  mapId: number | null;
}

export interface MapScrollActions {
  bottomExists: number | null;
  bottomMapId: number | null;
  id: number;
  leftExists: number | null;
  leftMapId: number | null;
  rightExists: number | null;
  rightMapId: number | null;
  topExists: number | null;
  topMapId: number | null;
}

export interface Modsters {
  id: number;
  itemId: number | null;
  modsterAchievements: string | null;
  modsterActiveSpells: string | null;
  modsterHiddenAchievements: string | null;
  modsterId: number | null;
  modsterPassiveSpells: string | null;
  order: number | null;
  parentsModsterId: string | null;
}

export interface MonsterDropChanceBonus {
  amount: number | null;
  id: number;
  type: number | null;
}

export interface MonsterDropChanceBonusCriterionsIdsJunction {
  MonsterDropChanceBonus_id: string | null;
  target_id: string | null;
}

export interface MonsterMiniBoss {
  id: number;
  monsterReplacingId: number | null;
}

export interface MonsterRaces {
  aggressiveAttackDelay: number | null;
  aggressiveImmunityCriterion: string | null;
  aggressiveLevelDiff: number | null;
  aggressiveZoneSize: number | null;
  id: number;
  monsters: string | null;
  nameId: number | null;
  superRaceId: number | null;
}

export interface Monsters {
  aggressiveAttackDelay: number | null;
  aggressiveImmunityCriterion: string | null;
  aggressiveLevelDiff: number | null;
  aggressiveZoneSize: number | null;
  animFunList: string | null;
  characRatios: string | null;
  correspondingMiniBossId: number | null;
  creatureBoneId: number | null;
  drops: string | null;
  favoriteSubareaId: number | null;
  gfxId: number | null;
  grades: string | null;
  id: number;
  incompatibleChallenges: string | null;
  incompatibleIdols: string | null;
  look: string | null;
  m_flags: number | null;
  nameId: number | null;
  race: number | null;
  scaleGradeRef: number | null;
  speedAdjust: number | null;
  spellGrades: string | null;
  spells: string | null;
  subareas: string | null;
  temporisDrops: string | null;
}

export interface MonsterSuperRaces {
  id: number;
  nameId: number | null;
}

export interface MonsterXPBonus {
  amount: number | null;
  id: number;
  type: number | null;
}

export interface MonsterXPBonusCriterionsIdsJunction {
  MonsterXPBonus_id: string | null;
  target_id: string | null;
}

export interface Months {
  id: number;
  nameId: number | null;
}

export interface MountBehaviors {
  descriptionId: number | null;
  id: number;
  nameId: number | null;
}

export interface MountBones {
  id: number;
}

export interface MountFamily {
  headUri: string | null;
  id: number;
  nameId: number | null;
}

export interface Mounts {
  certificateId: number | null;
  effects: string | null;
  familyId: number | null;
  id: number;
  look: string | null;
  nameId: number | null;
}

export interface NamingRules {
  id: number;
  maxLength: number | null;
  minLength: number | null;
  regexp: string | null;
}

export interface Notifications {
  cantBeClosed: number | null;
  iconId: number | null;
  id: number;
  messageId: string | null;
  titleId: string | null;
  trigger: string | null;
  typeId: number | null;
}

export interface NpcActions {
  id: number;
  nameId: number | null;
  realId: number | null;
}

export interface NpcMessages {
  id: number;
  messageId: string | null;
  messageParams: string | null;
}

export interface Npcs {
  actions: string | null;
  animFunList: string | null;
  dialogMessages: string | null;
  dialogReplies: string | null;
  fastAnimsFun: number | null;
  gender: number | null;
  id: number;
  look: string | null;
  nameId: number | null;
  tooltipVisible: number | null;
}

export interface OptionalFeatures {
  activationCriterions: string | null;
  id: number;
  isActivationOnLaunch: number | null;
  isActivationOnServerConnection: number | null;
  isClient: number | null;
  isServer: number | null;
  keyword: string | null;
}

export interface Ornaments {
  assetId: number | null;
  iconId: number | null;
  id: number;
  nameId: number | null;
  order: number | null;
  visible: number | null;
}

export interface Pack {
  hasSubAreas: number | null;
  id: number;
  name: string | null;
}

export interface Playlists {
  crossfadeDuration: number | null;
  id: number;
  random: number | null;
  sounds: string | null;
  startRandom: number | null;
  startRandomOnce: number | null;
  type: number | null;
}

export interface PointOfInterest {
  categoryId: number | null;
  id: number;
  nameId: number | null;
}

export interface PointOfInterestCategory {
  id: number;
}

export interface PopupInformations {
  autoTrigger: number | null;
  buttons: string | null;
  cacheType: number | null;
  criterion: string | null;
  descriptionId: number | null;
  id: number;
  illuName: string | null;
  parentId: number | null;
  titleId: string | null;
}

export interface PresetIcons {
  id: number;
  order: number | null;
}

export interface QuestCategory {
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface QuestCategoryQuestIdsJunction {
  QuestCategory_id: string | null;
  target_id: string | null;
}

export interface QuestKamasBonus {
  amount: number | null;
  id: number;
  type: number | null;
}

export interface QuestKamasBonusCriterionsIdsJunction {
  QuestKamasBonus_id: string | null;
  target_id: string | null;
}

export interface QuestObjectiveBringItemToNpc {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveBringSoulToNpc {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveCraftItem {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveDiscoverMap {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveDiscoverSubArea {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveFightMonster {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveFightMonstersOnMap {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveFreeForm {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveGoToNpc {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveMultiFightMonster {
  coords: string | null;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string | null;
  stepId: number | null;
  typeId: number | null;
}

export interface QuestObjectiveTypes {
  id: number;
  nameId: number | null;
}

export interface Quests {
  categoryId: number | null;
  followable: number | null;
  id: number;
  isDungeonQuest: number | null;
  isEvent: number | null;
  isPartyQuest: number | null;
  levelMax: number | null;
  levelMin: number | null;
  nameId: number | null;
  repeatLimit: number | null;
  repeatType: number | null;
  startCriterion: string | null;
}

export interface QuestsStepIdsJunction {
  Quests_id: string | null;
  target_id: string | null;
}

export interface QuestStepRewards {
  emotesReward: string | null;
  experienceRatio: number | null;
  id: number;
  itemsReward: string | null;
  jobsReward: string | null;
  kamasRatio: number | null;
  kamasScaleWithPlayerLevel: number | null;
  levelMax: number | null;
  levelMin: number | null;
  spellsReward: string | null;
  stepId: number | null;
  titlesReward: string | null;
}

export interface QuestSteps {
  descriptionId: number | null;
  dialogId: number | null;
  duration: number | null;
  id: number;
  nameId: number | null;
  optimalLevel: number | null;
  questId: number | null;
}

export interface QuestStepsObjectiveIdsJunction {
  QuestSteps_id: string | null;
  target_id: string | null;
}

export interface QuestStepsRewardsIdsJunction {
  QuestSteps_id: string | null;
  target_id: string | null;
}

export interface QuestXPBonus {
  amount: number | null;
  id: number;
  type: number | null;
}

export interface QuestXPBonusCriterionsIdsJunction {
  QuestXPBonus_id: string | null;
  target_id: string | null;
}

export interface RandomDropGroups {
  description: string | null;
  displayChances: number | null;
  displayContent: number | null;
  id: number;
  name: string | null;
  randomDropItems: string | null;
}

export interface Recipes {
  changeVersion: string | null;
  id: string;
  jobId: number | null;
  quantities: string | null;
  resultId: number | null;
  resultLevel: number | null;
  resultNameId: string | null;
  resultTypeId: number | null;
  skillId: number | null;
  tooltipExpirationDate: string | null;
}

export interface RecipesIngredientIdsJunction {
  Recipes_id: string | null;
  target_id: string | null;
}

export interface RideFood {
  familyId: number | null;
  gid: number | null;
  id: string;
  typeId: number | null;
}

export interface ServerCommunities {
  defaultCountries: string | null;
  id: number;
  nameId: number | null;
  namingRuleAdminId: number | null;
  namingRuleAllianceNameId: number | null;
  namingRuleAllianceTagId: number | null;
  namingRuleGuildNameId: number | null;
  namingRuleModoId: number | null;
  namingRuleMountNameId: number | null;
  namingRuleNameGeneratorId: number | null;
  namingRulePartyNameId: number | null;
  namingRulePlayerNameId: number | null;
  namingRulePresetNameId: number | null;
  shortId: string | null;
}

export interface ServerCommunitiesSupportedLangIdsJunction {
  ServerCommunities_id: string | null;
  target_id: string | null;
}

export interface ServerGameTypes {
  descriptionId: number | null;
  id: number;
  nameId: number | null;
  rulesId: string | null;
  selectableByPlayer: number | null;
}

export interface ServerLangs {
  id: number;
  langCode: string | null;
  nameId: number | null;
}

export interface ServerPopulations {
  id: number;
  nameId: number | null;
  weight: number | null;
}

export interface Servers {
  commentId: string | null;
  communityId: number | null;
  gameTypeId: number | null;
  id: number;
  illus: string | null;
  language: string | null;
  monoAccount: number | null;
  nameId: number | null;
  openingDate: number | null;
  populationId: number | null;
  restrictedToLanguages: string | null;
}

export interface ServerSeasons {
  beginning: number | null;
  closure: number | null;
  flagObjectId: number | null;
  id: string;
  nameId: string | null;
  resetDate: number | null;
  uid: number | null;
}

export interface Signs {
  id: number;
  paramsString: string | null;
  skillId: number | null;
  textKey: string | null;
}

export interface SkillNames {
  id: number;
  nameId: number | null;
}

export interface Skills {
  availableInHouse: number | null;
  clientDisplay: number | null;
  cursor: number | null;
  elementActionId: number | null;
  gatheredRessourceItem: number | null;
  id: number;
  interactiveId: number | null;
  isForgemagus: number | null;
  levelMin: number | null;
  nameId: number | null;
  parentJobId: number | null;
  range: number | null;
  useAnimation: string | null;
  useRangeInClient: number | null;
}

export interface SkillsCraftableItemIdsJunction {
  Skills_id: string | null;
  target_id: string | null;
}

export interface SkillsModifiableItemTypeIdsJunction {
  Skills_id: string | null;
  target_id: string | null;
}

export interface SkinMappings {
  id: number;
  lowDefId: number | null;
}

export interface SkinSlotsRules {
  id: string;
  skinId: number | null;
  slotRulesList: string | null;
}

export interface SmileyCategories {
  gfxId: string | null;
  id: number;
  isFake: number | null;
  order: number | null;
}

export interface SmileyPacks {
  id: number;
  nameId: number | null;
  order: number | null;
  smileys: string | null;
}

export interface Smileys {
  categoryId: number | null;
  forPlayers: number | null;
  gfxId: string | null;
  id: number;
  order: number | null;
  referenceId: number | null;
  triggers: string | null;
}

export interface SocialRights {
  groupId: number | null;
  id: number;
  nameId: number | null;
  order: number | null;
}

export interface SoundBones {
  animSounds: string | null;
  id: string;
}

export interface SoundUi {
  closeFile: string | null;
  id: number;
  openFile: string | null;
  uiName: string | null;
}

export interface SoundUiHook {
  id: number;
  name: string | null;
}

export interface SpeakingItemsText {
  id: string;
  textId: number | null;
  textLevel: number | null;
  textProba: number | null;
  textRestriction: string | null;
  textSound: number | null;
  textStringId: string | null;
}

export interface SpeakingItemsTriggers {
  id: string;
  states: string | null;
  triggersId: number | null;
}

export interface SpeakingItemsTriggersTextIdsJunction {
  SpeakingItemsTriggers_id: string | null;
  target_id: string | null;
}

export interface SpellBombs {
  chainReactionSpellId: number | null;
  comboCoeff: number | null;
  explodSpellId: number | null;
  id: number;
  instantSpellId: number | null;
  wallId: number | null;
}

export interface SpellConversions {
  id: string;
  newSpellId: number | null;
  oldSpellId: number | null;
}

export interface SpellLevels {
  apCost: number | null;
  criticalEffect: string | null;
  criticalHitProbability: number | null;
  effects: string | null;
  globalCooldown: number | null;
  grade: number | null;
  id: number;
  initialCooldown: number | null;
  m_flags: number | null;
  maxCastPerTarget: number | null;
  maxCastPerTurn: number | null;
  maxStack: number | null;
  minCastInterval: number | null;
  minPlayerLevel: number | null;
  minRange: number | null;
  previewZones: string | null;
  range: number | null;
  spellBreed: number | null;
  spellId: number | null;
  statesCriterion: string | null;
}

export interface SpellPairs {
  descriptionId: number | null;
  iconId: number | null;
  id: number;
  nameId: number | null;
}

export interface Spells {
  adminName: string | null;
  basePreviewZoneDescr: string | null;
  boundScriptUsageData: string | null;
  criticalHitBoundScriptUsageData: string | null;
  descriptionId: number | null;
  iconId: number | null;
  id: number;
  m_flags: number | null;
  nameId: number | null;
  order: number | null;
  scriptId: number | null;
  scriptIdCritical: number | null;
  scriptParams: string | null;
  scriptParamsCritical: string | null;
  spellLevels: string | null;
  typeId: number | null;
}

export interface SpellScripts {
  id: string;
  rawParams: string | null;
  type: number | null;
}

export interface SpellStates {
  cantBeMoved: number | null;
  cantBePushed: number | null;
  cantBeTackled: number | null;
  cantDealDamage: number | null;
  cantSwitchPosition: number | null;
  cantTackle: number | null;
  displayTurnRemaining: number | null;
  icon: string | null;
  iconVisibilityMask: number | null;
  id: number;
  incurable: number | null;
  invulnerable: number | null;
  invulnerableMelee: number | null;
  invulnerableRange: number | null;
  isMainState: number | null;
  isSilent: number | null;
  nameId: number | null;
  preventsFight: number | null;
  preventsSpellCast: number | null;
}

export interface SpellStatesEffectsIdsJunction {
  SpellStates_id: string | null;
  target_id: string | null;
}

export interface SpellTypes {
  id: number;
  longNameId: string | null;
  shortNameId: string | null;
}

export interface SpellVariants {
  breedId: number | null;
  id: number;
}

export interface SpellVariantsSpellIdsJunction {
  SpellVariants_id: string | null;
  target_id: string | null;
}

export interface StealthBones {
  id: number;
}

export interface SubAreas {
  achievements: string | null;
  areaId: number | null;
  associatedZaapMapId: number | null;
  basicAccountAllowed: number | null;
  bounds: string | null;
  capturable: number | null;
  customWorldMap: string | null;
  displayOnWorldMap: number | null;
  exploreAchievementId: number | null;
  harvestables: string | null;
  id: number;
  isConquestVillage: number | null;
  level: number | null;
  monsters: string | null;
  mountAutoTripAllowed: number | null;
  nameId: number | null;
  neighbors: string | null;
  packId: number | null;
  psiAllowed: number | null;
  shape: string | null;
}

export interface SubAreasEntranceMapIdsJunction {
  SubAreas_id: string | null;
  target_id: string | null;
}

export interface SubAreasExitMapIdsJunction {
  SubAreas_id: string | null;
  target_id: string | null;
}

export interface SubAreasMapIdsJunction {
  SubAreas_id: string | null;
  target_id: string | null;
}

export interface Subhints {
  hintAnchor: number | null;
  hintAnchoredElement: string | null;
  hintCreationDate: number | null;
  hintHeight: number | null;
  hintHighlightedElement: string | null;
  hintId: number | null;
  hintOrder: number | null;
  hintParentUid: string | null;
  hintPositionX: number | null;
  hintPositionY: number | null;
  hintTooltipOffsetX: number | null;
  hintTooltipOffsetY: number | null;
  hintTooltipPositionEnum: number | null;
  hintTooltipText: string | null;
  hintTooltipUrl: string | null;
  hintTooltipWidth: number | null;
  hintWidth: number | null;
  id: string;
}

export interface SuperAreas {
  hasWorldMap: number | null;
  id: number;
  nameId: number | null;
  worldmapId: number | null;
}

export interface TaxCollectorFirstnames {
  firstnameId: string | null;
  id: number;
}

export interface TaxCollectorNames {
  id: number;
  nameId: number | null;
}

export interface TextIconReferences {
  gfxId: string | null;
  id: number;
  referenceKey: string | null;
}

export interface Tips {
  descId: string | null;
  id: number;
}

export interface TitleCategories {
  id: number;
  nameId: number | null;
}

export interface Titles {
  categoryId: number | null;
  id: number;
  nameFemaleId: string | null;
  nameMaleId: string | null;
  visible: number | null;
}

export interface Translations {
  id: string | null;
  lang: string | null;
  value: string | null;
}

export interface VeteranRewards {
  id: number;
  itemGID: number | null;
  itemQuantity: number | null;
  requiredSubDays: number | null;
}

export interface Waypoints {
  activated: number | null;
  id: number;
  mapId: number | null;
  subAreaId: number | null;
}

export interface Weapons {
  apCost: number | null;
  appearanceId: number | null;
  castInDiagonal: number | null;
  castInLine: number | null;
  castTestLos: number | null;
  changeVersion: string | null;
  craftConditional: string | null;
  craftFeasible: string | null;
  craftVisible: string | null;
  craftXpRatio: number | null;
  criteria: string | null;
  criteriaTarget: string | null;
  criticalFailureProbability: number | null;
  criticalHitBonus: number | null;
  criticalHitProbability: number | null;
  descriptionId: number | null;
  favoriteRecyclingSubareas: string | null;
  favoriteSubAreas: string | null;
  favoriteSubAreasBonus: number | null;
  iconId: number | null;
  id: number;
  importantNoticeId: string | null;
  isColorable: number | null;
  itemSetId: number | null;
  level: number | null;
  m_flags: number | null;
  maxCastPerTurn: number | null;
  minRange: number | null;
  nameId: number | null;
  possibleEffects: string | null;
  price: number | null;
  range: number | null;
  realWeight: number | null;
  recipeSlots: number | null;
  recyclingNuggets: number | null;
  resourcesBySubarea: string | null;
  tooltipExpirationDate: string | null;
  typeId: number | null;
  useAnimationId: number | null;
  visibility: string | null;
}

export interface WeaponsDropMonsterIdsJunction {
  target_id: string | null;
  Weapons_id: string | null;
}

export interface WeaponsDropTemporisMonsterIdsJunction {
  target_id: string | null;
  Weapons_id: string | null;
}

export interface WeaponsEvolutiveEffectIdsJunction {
  target_id: string | null;
  Weapons_id: string | null;
}

export interface WeaponsRecipeIdsJunction {
  target_id: string | null;
  Weapons_id: string | null;
}

export interface WorldEvents {
  areas: string | null;
  categoryId: number | null;
  deletedObjects: string | null;
  dungeonHunterGroupsPerMap: number | null;
  endMsgId: number | null;
  fightScenarios: string | null;
  globalDrops: string | null;
  id: number;
  monsterHunterGroupsPerMap: number | null;
  nameId: number | null;
  preMsgDelay: number | null;
  preMsgId: number | null;
  scoreMsgTiming: number | null;
  startMsgId: number | null;
  subareas: string | null;
}

export interface WorldMaps {
  id: number;
  mapHeight: number | null;
  mapWidth: number | null;
  maxScale: number | null;
  minScale: number | null;
  nameId: number | null;
  origineX: number | null;
  origineY: number | null;
  startScale: number | null;
  totalHeight: number | null;
  totalWidth: number | null;
  viewableEverywhere: number | null;
  visibleOnMap: number | null;
  zoom: string | null;
}

export interface DB {
  AbuseReasons: AbuseReasons;
  AchievementCategories: AchievementCategories;
  AchievementCategories_achievementIds_junction: AchievementCategoriesAchievementIdsJunction;
  AchievementObjectives: AchievementObjectives;
  AchievementProgress: AchievementProgress;
  AchievementProgressSteps: AchievementProgressSteps;
  AchievementRewards: AchievementRewards;
  Achievements: Achievements;
  Achievements_objectiveIds_junction: AchievementsObjectiveIdsJunction;
  Achievements_rewardIds_junction: AchievementsRewardIdsJunction;
  ActionFilters: ActionFilters;
  ActivitySuggestions: ActivitySuggestions;
  ActivitySuggestionsCategories: ActivitySuggestionsCategories;
  AlignmentGift: AlignmentGift;
  AlignmentOrder: AlignmentOrder;
  AlignmentRank: AlignmentRank;
  AlignmentRankJntGift: AlignmentRankJntGift;
  AlignmentSides: AlignmentSides;
  AlignmentTitles: AlignmentTitles;
  AllianceRankNameSuggestions: AllianceRankNameSuggestions;
  AllianceRanks: AllianceRanks;
  AllianceRightGroups: AllianceRightGroups;
  AllianceRights: AllianceRights;
  AllianceTags: AllianceTags;
  AllianceTagsTypes: AllianceTagsTypes;
  AlmanaxCalendars: AlmanaxCalendars;
  AlmanaxCalendars_bonusesIds_junction: AlmanaxCalendarsBonusesIdsJunction;
  AlterationCategories: AlterationCategories;
  Alterations: Alterations;
  Appearances: Appearances;
  Areas: Areas;
  ArenaLeagueRewards: ArenaLeagueRewards;
  ArenaLeagues: ArenaLeagues;
  ArenaLeagueSeasons: ArenaLeagueSeasons;
  Bonuses: Bonuses;
  Bonuses_criterionsIds_junction: BonusesCriterionsIdsJunction;
  BonusesAreaCriterion: BonusesAreaCriterion;
  BonusesCriterions: BonusesCriterions;
  BonusesEquippedItemCriterion: BonusesEquippedItemCriterion;
  BonusesMonsterCriterion: BonusesMonsterCriterion;
  BonusesMonsterFamilyCriterion: BonusesMonsterFamilyCriterion;
  BonusesQuestCategoryCriterion: BonusesQuestCategoryCriterion;
  BonusesSubAreaCriterion: BonusesSubAreaCriterion;
  BreachBosses: BreachBosses;
  BreachDungeonModificators: BreachDungeonModificators;
  BreachInfinityLevels: BreachInfinityLevels;
  BreachPrizes: BreachPrizes;
  BreachWorldMapCoordinates: BreachWorldMapCoordinates;
  BreachWorldMapSectors: BreachWorldMapSectors;
  BreedRoles: BreedRoles;
  Breeds: Breeds;
  CensoredContents: CensoredContents;
  CensoredWords: CensoredWords;
  Challenges: Challenges;
  CharacteristicCategories: CharacteristicCategories;
  CharacteristicCategories_characteristicIds_junction: CharacteristicCategoriesCharacteristicIdsJunction;
  Characteristics: Characteristics;
  CharacterXPMappings: CharacterXPMappings;
  ChatChannels: ChatChannels;
  Choices: Choices;
  Collectables: Collectables;
  Collections: Collections;
  CompanionCharacteristics: CompanionCharacteristics;
  Companions: Companions;
  CompanionSpells: CompanionSpells;
  CreatureBonesOverrides: CreatureBonesOverrides;
  CreatureBonesTypes: CreatureBonesTypes;
  CustomModeBreedSpells: CustomModeBreedSpells;
  DependencyPaths: DependencyPaths;
  Documents: Documents;
  Dungeons: Dungeons;
  Dungeons_mapIds_junction: DungeonsMapIdsJunction;
  EffectInstanceDice: EffectInstanceDice;
  Effects: Effects;
  EmblemBackgrounds: EmblemBackgrounds;
  EmblemSymbolCategories: EmblemSymbolCategories;
  EmblemSymbols: EmblemSymbols;
  Emoticons: Emoticons;
  EvolutiveEffects: EvolutiveEffects;
  EvolutiveItemTypes: EvolutiveItemTypes;
  ExpeditionSeasons: ExpeditionSeasons;
  ExternalNotifications: ExternalNotifications;
  FeatureDescriptions: FeatureDescriptions;
  FightScenarios: FightScenarios;
  FinishMoves: FinishMoves;
  ForgettableSpells: ForgettableSpells;
  GuildChestTabs: GuildChestTabs;
  GuildRankNameSuggestions: GuildRankNameSuggestions;
  GuildRanks: GuildRanks;
  GuildRightGroups: GuildRightGroups;
  GuildRights: GuildRights;
  GuildTags: GuildTags;
  GuildTagsTypes: GuildTagsTypes;
  HavenbagFurnitures: HavenbagFurnitures;
  HavenbagThemes: HavenbagThemes;
  Heads: Heads;
  HintCategory: HintCategory;
  Hints: Hints;
  Houses: Houses;
  IncarnationLevels: IncarnationLevels;
  InfoMessages: InfoMessages;
  Interactives: Interactives;
  Items: Items;
  Items_dropMonsterIds_junction: ItemsDropMonsterIdsJunction;
  Items_dropTemporisMonsterIds_junction: ItemsDropTemporisMonsterIdsJunction;
  Items_evolutiveEffectIds_junction: ItemsEvolutiveEffectIdsJunction;
  Items_recipeIds_junction: ItemsRecipeIdsJunction;
  ItemSets: ItemSets;
  ItemSuperTypes: ItemSuperTypes;
  ItemTypes: ItemTypes;
  Jobs: Jobs;
  KothRoles: KothRoles;
  LegendaryPowersCategories: LegendaryPowersCategories;
  LegendaryTreasureHunts: LegendaryTreasureHunts;
  LivingObjectSkinJntMood: LivingObjectSkinJntMood;
  LuaFormulas: LuaFormulas;
  MapCoordinates: MapCoordinates;
  MapCoordinates_mapIds_junction: MapCoordinatesMapIdsJunction;
  MapPositions: MapPositions;
  MapReferences: MapReferences;
  MapScrollActions: MapScrollActions;
  Modsters: Modsters;
  MonsterDropChanceBonus: MonsterDropChanceBonus;
  MonsterDropChanceBonus_criterionsIds_junction: MonsterDropChanceBonusCriterionsIdsJunction;
  MonsterMiniBoss: MonsterMiniBoss;
  MonsterRaces: MonsterRaces;
  Monsters: Monsters;
  MonsterSuperRaces: MonsterSuperRaces;
  MonsterXPBonus: MonsterXPBonus;
  MonsterXPBonus_criterionsIds_junction: MonsterXPBonusCriterionsIdsJunction;
  Months: Months;
  MountBehaviors: MountBehaviors;
  MountBones: MountBones;
  MountFamily: MountFamily;
  Mounts: Mounts;
  NamingRules: NamingRules;
  Notifications: Notifications;
  NpcActions: NpcActions;
  NpcMessages: NpcMessages;
  Npcs: Npcs;
  OptionalFeatures: OptionalFeatures;
  Ornaments: Ornaments;
  Pack: Pack;
  Playlists: Playlists;
  PointOfInterest: PointOfInterest;
  PointOfInterestCategory: PointOfInterestCategory;
  PopupInformations: PopupInformations;
  PresetIcons: PresetIcons;
  QuestCategory: QuestCategory;
  QuestCategory_questIds_junction: QuestCategoryQuestIdsJunction;
  QuestKamasBonus: QuestKamasBonus;
  QuestKamasBonus_criterionsIds_junction: QuestKamasBonusCriterionsIdsJunction;
  QuestObjectiveBringItemToNpc: QuestObjectiveBringItemToNpc;
  QuestObjectiveBringSoulToNpc: QuestObjectiveBringSoulToNpc;
  QuestObjectiveCraftItem: QuestObjectiveCraftItem;
  QuestObjectiveDiscoverMap: QuestObjectiveDiscoverMap;
  QuestObjectiveDiscoverSubArea: QuestObjectiveDiscoverSubArea;
  QuestObjectiveFightMonster: QuestObjectiveFightMonster;
  QuestObjectiveFightMonstersOnMap: QuestObjectiveFightMonstersOnMap;
  QuestObjectiveFreeForm: QuestObjectiveFreeForm;
  QuestObjectiveGoToNpc: QuestObjectiveGoToNpc;
  QuestObjectiveMultiFightMonster: QuestObjectiveMultiFightMonster;
  QuestObjectiveTypes: QuestObjectiveTypes;
  Quests: Quests;
  Quests_stepIds_junction: QuestsStepIdsJunction;
  QuestStepRewards: QuestStepRewards;
  QuestSteps: QuestSteps;
  QuestSteps_objectiveIds_junction: QuestStepsObjectiveIdsJunction;
  QuestSteps_rewardsIds_junction: QuestStepsRewardsIdsJunction;
  QuestXPBonus: QuestXPBonus;
  QuestXPBonus_criterionsIds_junction: QuestXPBonusCriterionsIdsJunction;
  RandomDropGroups: RandomDropGroups;
  Recipes: Recipes;
  Recipes_ingredientIds_junction: RecipesIngredientIdsJunction;
  RideFood: RideFood;
  ServerCommunities: ServerCommunities;
  ServerCommunities_supportedLangIds_junction: ServerCommunitiesSupportedLangIdsJunction;
  ServerGameTypes: ServerGameTypes;
  ServerLangs: ServerLangs;
  ServerPopulations: ServerPopulations;
  Servers: Servers;
  ServerSeasons: ServerSeasons;
  Signs: Signs;
  SkillNames: SkillNames;
  Skills: Skills;
  Skills_craftableItemIds_junction: SkillsCraftableItemIdsJunction;
  Skills_modifiableItemTypeIds_junction: SkillsModifiableItemTypeIdsJunction;
  SkinMappings: SkinMappings;
  SkinSlotsRules: SkinSlotsRules;
  SmileyCategories: SmileyCategories;
  SmileyPacks: SmileyPacks;
  Smileys: Smileys;
  SocialRights: SocialRights;
  SoundBones: SoundBones;
  SoundUi: SoundUi;
  SoundUiHook: SoundUiHook;
  SpeakingItemsText: SpeakingItemsText;
  SpeakingItemsTriggers: SpeakingItemsTriggers;
  SpeakingItemsTriggers_textIds_junction: SpeakingItemsTriggersTextIdsJunction;
  SpellBombs: SpellBombs;
  SpellConversions: SpellConversions;
  SpellLevels: SpellLevels;
  SpellPairs: SpellPairs;
  Spells: Spells;
  SpellScripts: SpellScripts;
  SpellStates: SpellStates;
  SpellStates_effectsIds_junction: SpellStatesEffectsIdsJunction;
  SpellTypes: SpellTypes;
  SpellVariants: SpellVariants;
  SpellVariants_spellIds_junction: SpellVariantsSpellIdsJunction;
  StealthBones: StealthBones;
  SubAreas: SubAreas;
  SubAreas_entranceMapIds_junction: SubAreasEntranceMapIdsJunction;
  SubAreas_exitMapIds_junction: SubAreasExitMapIdsJunction;
  SubAreas_mapIds_junction: SubAreasMapIdsJunction;
  Subhints: Subhints;
  SuperAreas: SuperAreas;
  TaxCollectorFirstnames: TaxCollectorFirstnames;
  TaxCollectorNames: TaxCollectorNames;
  TextIconReferences: TextIconReferences;
  Tips: Tips;
  TitleCategories: TitleCategories;
  Titles: Titles;
  translations: Translations;
  VeteranRewards: VeteranRewards;
  Waypoints: Waypoints;
  Weapons: Weapons;
  Weapons_dropMonsterIds_junction: WeaponsDropMonsterIdsJunction;
  Weapons_dropTemporisMonsterIds_junction: WeaponsDropTemporisMonsterIdsJunction;
  Weapons_evolutiveEffectIds_junction: WeaponsEvolutiveEffectIdsJunction;
  Weapons_recipeIds_junction: WeaponsRecipeIdsJunction;
  WorldEvents: WorldEvents;
  WorldMaps: WorldMaps;
}
